#!/bin/sh
# reflink_dedupe - A FreeBSD utility for deduplication using reflinks.
#
# Copyright (c) 2025, Sophia Hadash
# All rights reserved.
#
# Licensed under the BSD 2-Clause License. See LICENSE file for details.

# PROVIDE: reflink_dedupe
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="reflink_dedupe"
rcvar="reflink_dedupe_enable"

# Customize if you change the path
command="/usr/local/bin/reflink_dedupe"
pidfile="/var/run/reflink_dedupe.pid"
command_args="--daemon --watcher"
command_background="yes"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

load_rc_config $name
: ${reflink_dedupe_enable:="NO"}

run_rc_command "$1"
